// Every string the widget shows. Pass `text` to <Holagram /> to translate or reword any of them.
export const TEXT = {
  greeting: (owner: string) => `Hi! 👋 Let's get you in touch with ${owner}.`,
  identifyTitle: 'Identify yourself',
  identifyHint: (owner: string) => `${owner} will use your email to get back to you.`,
  nameLabel: 'Name',
  emailLabel: 'Email',
  continue: 'Continue',
  badEmail: "That doesn't look like a valid email.",
  askTopic: (first: string) => `Thanks, ${first}! What can I help you with?`,
  emailSent: (email: string) =>
    `📩 I just sent a confirmation link to ${email}. Open it to start the chat (it expires in 30 minutes). Check spam if you don't see it.`,
  resend: '↻ Resend the email',
  otherEmail: '✏️ Use another email',
  verified: (owner: string) => `✅ Email verified! You are now connected with ${owner}.`,
  connected: (owner: string) => `Go ahead, ${owner} will answer here.`,
  linkExpired: 'This link is invalid or has expired. Pick an option again and I will send you a new one.',
  verifyFailed: "Couldn't verify the link. Please try again.",
  offline: 'The chat is offline right now. Please try again later.',
  rateLimited: 'Too many requests. Please try again later.',
  slowDown: 'Slow down a little 🙂 try again in a while.',
  notSent: "That message didn't go through. Please try again.",
  anythingElse: 'Anything else?',
  placeholder: {
    name: 'Your full name',
    email: 'you@example.com',
    topic: 'Pick an option above',
    verify: 'Check your inbox…',
    chat: 'Write a message…',
  },
  open: 'Open chat',
  close: 'Close chat',
  dismiss: 'Hide chat button',
  newChat: 'Start a new chat',
  send: 'Send',
  dialog: (owner: string) => `Chat with ${owner}`,
}

export type HolagramText = typeof TEXT

/** Spanish strings: `<Holagram text={es} />`. */
export const es: HolagramText = {
  greeting: (owner) => `¡Hola! 👋 Te pongo en contacto con ${owner}.`,
  identifyTitle: 'Identifícate',
  identifyHint: (owner) => `${owner} usará tu email para responderte.`,
  nameLabel: 'Nombre',
  emailLabel: 'Email',
  continue: 'Continuar',
  badEmail: 'Ese email no parece válido.',
  askTopic: (first) => `¡Gracias, ${first}! ¿En qué te puedo ayudar?`,
  emailSent: (email) =>
    `📩 Te acabo de enviar un enlace de confirmación a ${email}. Ábrelo para empezar el chat (caduca en 30 minutos). Revisa el spam si no lo ves.`,
  resend: '↻ Reenviar el correo',
  otherEmail: '✏️ Usar otro email',
  verified: (owner) => `✅ ¡Email verificado! Ya estás en contacto con ${owner}.`,
  connected: (owner) => `Adelante, ${owner} te responderá aquí.`,
  linkExpired: 'Este enlace no es válido o ha caducado. Elige una opción de nuevo y te enviaré otro.',
  verifyFailed: 'No se pudo verificar el enlace. Inténtalo de nuevo.',
  offline: 'El chat no está disponible ahora mismo. Inténtalo más tarde.',
  rateLimited: 'Demasiadas solicitudes. Inténtalo más tarde.',
  slowDown: 'Más despacio 🙂 inténtalo en un rato.',
  notSent: 'Ese mensaje no se envió. Inténtalo de nuevo.',
  anythingElse: '¿Algo más?',
  placeholder: {
    name: 'Tu nombre completo',
    email: 'tu@ejemplo.com',
    topic: 'Elige una opción',
    verify: 'Revisa tu correo…',
    chat: 'Escribe un mensaje…',
  },
  open: 'Abrir chat',
  close: 'Cerrar chat',
  dismiss: 'Ocultar el botón del chat',
  newChat: 'Empezar un chat nuevo',
  send: 'Enviar',
  dialog: (owner) => `Chat con ${owner}`,
}
